on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      buildPath:
        type: string
        default: dist/frontend

jobs:
  build:
    name: Angular Build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      - name: Setup Node.js $
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Prepare Environment
        run: |
          npx ng g environments
          echo "${{ secrets.ANGULAR_ENVIRONMENT }}" > src/environments/environment.ts
          echo "${{ secrets.ANGULAR_ENVIRONMENT }}" > src/environments/environment.development.ts
      - name: Build
        run: npm run build:prod
      - uses: actions/upload-artifact@master
        with:
          name: dist-frontend-${{ github.sha }}
          path: frontend/dist
